# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOfficer',
            fields=[
                ('officer', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AdminOfficerToken',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AdminOfficer')),
            ],
        ),
        migrations.CreateModel(
            name='GuardCredentials',
            fields=[
                ('guard_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GuardSession',
            fields=[
                ('token', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('login_timestamp', models.DateTimeField(null=True)),
                ('logout_timestamp', models.DateTimeField(null=True)),
                ('guard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GuardCredentials')),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('location', models.AutoField(primary_key=True, serialize=False)),
                ('lattitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('timestamp', models.DateTimeField(null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GuardSession')),
            ],
        ),
    ]
