# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160529_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminofficertoken',
            name='login_timestamp',
        ),
        migrations.RemoveField(
            model_name='adminofficertoken',
            name='logout_timestamp',
        ),
        migrations.RemoveField(
            model_name='guardsession',
            name='login_timestamp',
        ),
        migrations.RemoveField(
            model_name='guardsession',
            name='logout_timestamp',
        ),
        migrations.RemoveField(
            model_name='locationdetails',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='adminofficertoken',
            name='logindate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='adminofficertoken',
            name='logintime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='adminofficertoken',
            name='logoutdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='adminofficertoken',
            name='logouttime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='guardsession',
            name='logindate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guardsession',
            name='logintime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='guardsession',
            name='logoutdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guardsession',
            name='logouttime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='locationdetails',
            name='arivaldate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='locationdetails',
            name='arivaltime',
            field=models.TimeField(null=True),
        ),
    ]
