# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_locationdetails_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdetails',
            name='location',
            field=models.AutoField(default=datetime.datetime(2016, 5, 27, 21, 12, 31, 315466, tzinfo=utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GuardSession'),
        ),
    ]
